import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Fundamentals',
      items: [{ type: 'autogenerated', dirName: 'fundamentals' }],
    },
    {
      type: 'category',
      label: 'Miscs',
      items: [
        { type: 'autogenerated', dirName: 'miscs' },
        {
          type: 'link',
          label: 'llms.txt',
          href: 'pathname:///llms.txt',
        },
      ],
    },
  ],
};

export default sidebars;
